config/routes.rb
Rails.application.routes.draw do
  
  resources :profiles
  resources :posts
  resources :friends, only: [:create, :destroy]
  
  resources :profiles do
    member do
      get :following, :followers
    end
  end
  
  
  resources :posts do
    resources :comments
  end
  
  resources :relationships, only: [:create, :destroy]
  devise_for :users, :controllers => { :registrations => "registrations" }
  
  
  root 'static_pages#front'
  get 'users/new'  
  get 'static_pages/front'
  get 'static_pages/about'
  
end

app/models/comment.rb
class Comment < ActiveRecord::Base
  belongs_to :profile
  belongs_to :post
  
  validates :body, presence: true, length: {in: 1..140}
  validates :profile_id, presence: true
  validates :post_id, presence: true
end

app/models/friend.rb
class Friend < ActiveRecord::Base
  belongs_to :follower, class_name: "Profile"
  belongs_to :followed, class_name: "Profile"
  
  validates :follower_id, presence: true
  validates :followed_id, presence: true
end

app/models/like.rb
class Like < ActiveRecord::Base
  belongs_to :profile
  belongs_to :post
  
  validates :profile_id, presence: true
  validates :post_id, presence: true
  
end

app/models/post.rb
class Post < ActiveRecord::Base
  belongs_to :user
  has_many :comments
  
  validates :content, presence: true, length: { maximum: 300 }
  validates :user_id, presence: true
  
  has_attached_file :photo, :styles => { :medium => "500x500>", :small => "200x200>" }, :default_url => "/images/:style/missing.png"
  validates_attachment_content_type :photo, :content_type => /\Aimage\/.*\Z/
  
end

app/models/profile.rb
class Profile < ActiveRecord::Base
  require "open-uri"
  has_many :comments
  belongs_to :user
  
  has_attached_file :avatar, :styles => { :medium => "300x300>", :thumb => "40x40>" }, :default_url => "/images/:style/missing.png"
  validates_attachment_content_type :avatar, :content_type => /\Aimage\/.*\Z/
  validates :name, presence: true, length: {in: 1..20 }
  validates :user_id, presence: true
  
  #friends
  has_many :active_friends, class_name: "Friend", foreign_key: "follower_id", dependent: :destroy
  has_many :following, through: :active_friends, source: :followed
  has_many :passive_friends, class_name: "Friend", foreign_key: "followed_id", dependent: :destroy
  has_many :followers, through: :passive_friends
  
  def following?(other_user)
     following.include?(other_user)
   end

   def follow(other_user)
     active_friends.create(followed_id: other_user.id)
   end

   def unfollow(other_user)
     active_friends.find_by(followed_id: other_user.id).destroy
   end
  
   #avatar
  def picture_from_url(url)
    self.picture = URI.parse(url)
  end
  
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  has_many :posts
  has_one :profile
  
  #devise                                
  devise :database_authenticatable, :registerable, :recoverable, :rememberable, :trackable, :validatable
  accepts_nested_attributes_for :profile
           
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
  
  before_action :configure_permitted_parameters, if: :devise_controller?

   protected

   def configure_permitted_parameters
     devise_parameter_sanitizer.for(:sign_up) { |u| u.permit(:username, :email, :password, :password_confirmation, :remember_me) }
     devise_parameter_sanitizer.for(:sign_in) { |u| u.permit(:login, :username, :email, :password, :remember_me) }
     devise_parameter_sanitizer.for(:account_update) { |u| u.permit(:username, :email, :password, :password_confirmation, :current_password) }
   end
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController
  before_action :authenticate_user!, only: [:new, :create]
  
  def show
    
  end
  
  def new
  end
  
  def create
    @profile = Profile.where(:id => current_user.id).first
    @post = Post.find(params[:post_id])
    @comment = @post.comments.build(comment_params)
    puts @profile
    @comment.profile = @profile
    if @comment.save
      redirect_to post_path(@post)
    end
    
  end
  
  private
  def comment_params
    params.require(:comment).permit(:body)
  end
end

app/controllers/friends_controller.rb
class FriendsController < ApplicationController
  
    def create
      user = Profile.find(params[:followed_id])
      current_user.profile.follow(user)
      redirect_to user
    end

    def destroy
      user = Friend.find(params[:id]).followed
      current_user.profile.unfollow(user)
      redirect_to user
    end
  
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
  
  def index
    if user_signed_in?
      @posts = Post.where(:user_id => current_user.id).paginate(:page => params[:page],:per_page => 5).order("created_at DESC")
          
    end
  end
  
  def show
    @post = Post.find(params[:id])
    
    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @post }
     end
    
  end
  
  def new
    @post = Post.new
  end
  
  def create
    @post = current_user.posts.build(post_params)
    if @post.save
      redirect_to @post
    else
      render 'new'
    end
  end
  
  private
  def post_params
    params.require(:post).permit(:content, :photo)
  end
  
end

app/controllers/profiles_controller.rb
class ProfilesController < ApplicationController
  
  before_action :authenticate_user!, only: [:new, :create, :update]
  
  def show
    @profile = Profile.where(:user_id => params[:id]).first
    @posts = Post.where(:user_id => params[:id]).paginate(:page => params[:page],:per_page => 5).order("created_at DESC")

  end
  
  def new
    @profile = Profile.new
  end
  
  def create
    @profile = Profile.new(profile_params)
    @profile.user_id = current_user.id
    if @profile.save
      redirect_to profile_path(@profile.user_id)
    end

  end
  
  def edit
    @profile = Profile.where(:user_id => params[:id]).first
  end
  
  def update    
    @profile = Profile.where(:user_id => params[:id]).first
    
    if @profile.update_attributes(profile_params)
      redirect_to profile_path(@profile.user_id)
    else
      render 'edit'
    end
    
  end
  
  def following
      @title = "Following"
      @user  = Profile.find(params[:id])
      @users = @user.following.paginate(page: params[:page],:per_page => 5)
      render 'show_follow'
    end

    def followers
      @title = "Followers"
      @user  = Profile.find(params[:id])
      @users = @user.followers.paginate(page: params[:page],:per_page => 5)
      render 'show_follow'
    end

  private
  def profile_params
    params.require(:profile).permit(:name, :location, :avatar)
  end
  
end

app/controllers/registrations_controller.rb
class RegistrationsController < Devise::RegistrationsController
  protected

  def after_sign_up_path_for(resource)
    new_profile_path
  end
end

app/controllers/static_pages_controller.rb
class StaticPagesController < ApplicationController
  def front
    if user_signed_in?
      redirect_to posts_path
    else
      redirect_to new_user_registration_path
    end
  end

  def about
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/helpers/friends_helper.rb
module FriendsHelper
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/helpers/profiles_helper.rb
module ProfilesHelper
end

app/helpers/registrations_helper.rb
module RegistrationsHelper
end

app/helpers/static_pages_helper.rb
module StaticPagesHelper
end

app/views/friends/_follow.html.erb
<%= form_for(current_user.profile.active_friends.build) do |f| %>
	<%= hidden_field_tag :followed_id, @profile.id %>
    <%= f.submit "Follow", class: "btn btn-primary" %>
<% end %>

app/views/friends/_friend_stats.html.erb
<% @user ||= current_user.profile %>
	<%= link_to following_profile_path(@user) do %> <%= @user.following.count %> following <% end %><br>
	<%= link_to followers_profile_path(@user) do %> <%= @user.followers.count %> followers <% end %>
	

app/views/friends/_unfollow.html.erb
<%= form_for(current_user.profile.active_friends.find_by(followed_id: @profile.id), html: {method: :delete}) do |f| %>
  <%= f.submit "Unfollow", class: "btn btn-primary" %>
<% end %>

app/views/layouts/_header.html.erb
<header class="navbar navbar-fixed-top navbar-inverse">
  <div class="container">
    <%= link_to "imprint", root_path, id: "logo" %>
    <nav>
      <ul class="nav navbar-nav navbar-right">
		<% if user_signed_in? %>
         <li> <a class="dropdown-toggle" data-toggle="dropdown" href="#"><strong><%= current_user.username %></strong><span class="caret"></span></a>
          <ul class="dropdown-menu">
			  <li><%= link_to "View profile", profile_path(current_user.id), :class => 'navbar-link' %></li>  	
		  	  <li><%= link_to "Settings", edit_user_registration_path, :class => 'navbar-link' %></li>
		  	  <li><%= link_to "Logout", destroy_user_session_path, method: :delete, :class => 'navbar-link' %></li>
	  </ul>
 	 </li>
		<% else %>
		  <%= link_to "Sign up", new_user_registration_path, :class => 'navbar-link'  %> |
		  <%= link_to "Login", new_user_session_path, :class => 'navbar-link'  %>
		<% end %>
      </ul>
    </nav>
  </div>
</header>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title><%= yield(:title) %> | imprint</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>
    <%= render 'layouts/header' %>
    <div class="container">
		<% if notice %>
		  <p class="alert alert-success"><%= notice %></p>
		<% end %>
		<% if alert %>
		  <p class="alert alert-danger"><%= alert %></p>
		<% end %>
		<%= yield %>
	</div>
</body>
</html>

app/views/posts/index.html.erb
<% provide(:title, "All your imprints") %>

<% if user_signed_in? %>
<p>
	<%= link_to new_post_path do %>New<% end %>
</p>

		<% @posts.each do |p| %>
		<div id="container">
		   <div id="image"><%= image_tag p.photo.url(:medium) if p.photo.present?  %></div>
		    <p id="imagetext">
		        <%= link_to controller: "posts", action: "show", id: p do  %><%= p.content %><% end %>
		    </p>
		</div>
		<p>Created by <%= link_to profile_path(p.user_id) do %><%= p.user.username %> <% end %></p>
		<br>
		
		<%= will_paginate @posts %>
		<% end %>
</div>
<%= link_to new_post_path do %>New<% end %>

<% else %>
	<p>Please sign up or sign in.</p>
<% end %>

app/views/posts/new.html.erb
<% provide(:title, "New imprint") %>

<center><h3>Create a new imprint</h3>


<%= form_for @post do |f| %>
    <p>
      <%= f.text_area:content, :required => true, :cols => "60", :rows => "10", :maxlength => "299" %>
    </p>
	<p>
		<p><%= f.file_field :photo %></p>
	</p>
    <p>
	  <button type="submit" class="btn btn-default">Submit</button>
    </p>
<% end %>
</center>

app/views/posts/show.html.erb
<% provide(:title, "Your imprint") %>

<div id="container">
   <div id="image"><%= image_tag @post.photo.url(:medium) if @post.photo.present?  %></div>
    <p id="imagetext">
        <%= @post.content %>
    </p>
</div>

<p>Comments:</p>
<p>
<% @post.comments.each do |c| %>
	<p><%= link_to profile_path(c.profile.id) do %><%= c.profile.name %> <% end %></p>
	<p><%= c.body %></p>
<% end %>
</p>
<p>Make a new comment</p>
<%= form_for ([@post, @post.comments.build]) do |f|  %>
	<p>
		<%= f.label :body%>
		<%= f.text_area :body %>
	</p>
	
	<p>
		<%= f.submit %>
	</p>
<% end %>

app/views/profiles/edit.html.erb
<% provide(:title, "Edit your profile") %>



<%= form_for @profile do |f| %>

	<p><%= f.file_field :avatar %></p>
	
    <p><%= f.label :name, "Update name" %></p>
    <p><%= f.text_field :name, autofocus: true, autocomplete: "off" %></p>

    <p><%= f.label :location, "Update your location" %></p>
    <p><%= f.text_field :location, autofocus: true, autocomplete: "off" %></p>

    <%= f.submit "Change my profile" %>
<% end %>

app/views/profiles/new.html.erb
<center><h3>Your profile</h3>


<%= form_for @profile do |f| %>

	<p><%= f.file_field :avatar %></p>
	
    <p><%= f.label :name, "Update name" %></p>
    <p><%= f.text_field :name, autofocus: true, autocomplete: "off" %></p>

    <p><%= f.label :location, "Update your location" %></p>
    <p><%= f.text_field :location, autofocus: true, autocomplete: "off" %></p>

    <%= f.submit "Change my profile" %>
<% end %>

app/views/profiles/show.html.erb
<% provide(:title, "Your profile") %>

<div id="profilepage">
	<div id="profiledata">
		<%= image_tag @profile.avatar.url(:medium) %>
		<h3><%= @profile.name %></h3>
		<p><%= @profile.user.username  %></p>
		<%= render 'friends/friend_stats' %>
		<br><br>
		<p>Bio: lorem ipsum blah lorem.</p>
		
		<p><%= @profile.location %></p>
		<%= link_to edit_profile_path(@profile.user_id) do %><button class="btn btn-default" type="submit">Edit profile</button>
		<% end %>
		
		<% if current_user.profile.following?(@profile)%>
		    <%= render 'friends/unfollow' %>
		<% else %>
		    <%= render 'friends/follow' %>
		<% end %>
		
	</div>
	<% if current_user.id == @profile.user.id %>
		<h3>Your imprints</h3>
	<% else %>
		<h3>Imprints</h3>
	<% end %>
	<div id="profilefeed">
		
		<% @posts.each do |p| %>
			<p id="image"><%= image_tag @profile.avatar.url(:thumb) %></p>
			<% if p.photo.present? %>
				<%= image_tag p.photo.url(:medium) %>
			<% end %>
			<p><%= p.content %></p>
			  <p>Created by <%= link_to profile_path(@profile.user_id) do %><%= @profile.name %> <% end %></p>
			<br>
		<% end %>
		<%= will_paginate @posts %>
	</div>
</div>

app/views/profiles/show_follow.html.erb
<% provide(:title, @title) %>

<h1><small><%= @title %>:</small></h1>
<br>
    <% if @users.any? %>
        <% @users.each do |u| %>
			<p><%= image_tag u.avatar.url(:thumb) %></p>
			<p><%= u.name %>,
			<%= u.user.username  %></p>

        	<%= will_paginate @users %>
		<% end %>
    <% end %>

app/views/static_pages/about.html.erb
<% provide(:title, "About") %>



<h1>StaticPages#about</h1>
<p>Find me in app/views/static_pages/about.html.erb</p>

app/views/static_pages/front.html.erb
<% provide(:title, "Welcome") %>


<h1>Welcome to Imprint.</h1>
<% if user_signed_in? %>
	<p>Here are your imprints...</p>
	<p>Create a new imprint <%= link_to new_post_path do %> <span class="glyphicon glyphicon-log-in"></span><% end %></p>
<% else %>
	<p>Please sign up or log in.</p>
	
<% end %>